name: Draft a release note
on:
  push:
    branches:
      - main
      - master
jobs:
  draft_release:
    name: Release Drafter
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Run release-drafter
        uses: release-drafter/release-drafter@v6.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
